// examples/react-example.jsx
import { useEffect, useRef, useState } from 'react';
import FlexiEditor from 'flexi-editor';
import 'flexi-editor/style.css';

function FlexiEditorComponent({ initialContent = '', onChange }) {
    const editorRef = useRef(null);
    const instanceRef = useRef(null);
    const [isReady, setIsReady] = useState(false);

    useEffect(() => {
        if (editorRef.current && !instanceRef.current) {
            instanceRef.current = new FlexiEditor({
                element: editorRef.current,
                placeholder: 'Start typing...',
                content: initialContent
            });

            // Listen to changes
            instanceRef.current.on('change', () => {
                if (onChange) {
                    onChange(instanceRef.current.getData());
                }
            });

            instanceRef.current.on('ready', () => {
                setIsReady(true);
            });
        }

        return () => {
            if (instanceRef.current) {
                instanceRef.current.destroy();
                instanceRef.current = null;
            }
        };
    }, []);

    return (
        <div>
            <div ref={editorRef} />
            {isReady && <p>Editor is ready!</p>}
        </div>
    );
}

export default FlexiEditorComponent;

// examples/vue-example.vue
<template>
    <div>
        <div ref="editorElement"></div>
        <p v-if="isReady">Editor is ready!</p>
    </div>
</template>

<script>
import FlexiEditor from 'flexi-editor';
import 'flexi-editor/style.css';

export default {
    name: 'FlexiEditorComponent',
    props: {
        initialContent: {
            type: String,
            default: ''
        }
    },
    data() {
        return {
            editor: null,
            isReady: false
        };
    },
    mounted() {
        this.editor = new FlexiEditor({
            element: this.$refs.editorElement,
            placeholder: 'Start typing...',
            content: this.initialContent
        });

        this.editor.on('change', () => {
            this.$emit('change', this.editor.getData());
        });

        this.editor.on('ready', () => {
            this.isReady = true;
        });
    },
    beforeUnmount() {
        if (this.editor) {
            this.editor.destroy();
        }
    }
};
</script>
